### ISSUE TITLE
Question: where to register openPN callback?

### ISSUE THREAD

**Issue by dirkpostma** [taivo/parse-push-plugin#24]
I got your plugin working for both iOS and Android. The only things that is not clear for me is: where should I register the openPN callback when using **ionic framework**?

If I wrap in $ionicPlatform.ready(function() {}, it DOES work for iOS, when coming from background, but not for a cold start. For Android, it doesn't work at all.

Do you have experience with the (wildly used) ionic framework? If so, can you 9or anyone else?) help me on this?

**Comment by trueicecold** [comment]
same goes for regular cordova usage (without ionic). when the app is started from push, openPN does not occur on iOS. only on returning from background because of push.

**Comment by taivo** [comment]
There was a bug with iOS cold start. I just fixed it.

Since `receivePN` is working for you, just register `openPN` at the same place. I think your issue may be because of the bug I just fixed. Update and let me know :)

**Comment by trueicecold** [comment]
Still not working...

I'm using:

```
ParsePushPlugin.on('openPN', function(pn) {
      alert(1);
      Config.FROM_PUSH = true;
});
```

no alert pops up when the app is opened from push.

Could it be the jsCallback is called before the "deviceReady" event?

**Comment by trueicecold** [comment]
I think it's exactly what's happening...

The jscallback from coldstart method is called before deviceready is made.
What I've done is save the userInfo from coldStart to an NSMutableDictionary, and implemented a new method called getIncoming, which return the saved variable. If I call getIncoming after deviceready, it works just fine.

Once I tidy up my code, I'll try and commit a fix.

**Comment by taivo** [comment]
Ah good catch. I took a stab at this myself and just checked in a fix before seeing your last message. 

In my fix, if the javascript callback is not yet registered, notifications get stored in a queue. When registration occurs in registerCallback(), the queue is flushed.

**Comment by devfelipereis** [comment]
For me it's not working either(Testing on Android). I have this code inside $ionicPlatform.ready().

```
ParsePushPlugin.on('openPN', function(pnObj){
          $state.go('app.messages', {builderId: pnObj.builderId, enterpriseId: pnObj.enterpriseId, fromPush: true});
      });
```

Nothing inside there is happening. Any solution?

**Comment by taivo** [comment]
I had sometime to revisit this issue. The underlying cause turns out to be timing related issues, including one where the plugin javascript triggers `openPN` before $ionicPlatform.ready() can setup an openPN handler. 

This explains the problem @devfelipereis encountered. When app is in background, openPN handlers are still ready to go. When app is truly cold-started via pn, there is a bit of a time gap between the plugin being ready (via onCordovaReady) and $ionicPlatform.ready().

Should be fixed now as mentioned in the commit above this post.

**Comment by taivo** [comment]
iOS part of this problem is also fixed. Most of it is the same as the Android problem mentioned above and was fixed by the same javascript code.

On cold start, iOS formatted the notification payload a bit differently so some tinkering with objective C was necessary to make the payload consistent again.

Closing this issue. Thank you all for your feedback.

PS: I've added an ionic app and a simple parse-server that can be used to test these issues more quickly and verify if something works/fail more easily. Also, I've simplified installation by A LOT. Just add the plugin and set a few config.xml parameters now. No more mucking with java or objective C just to use this plugin.

So try it out, and let me know. Thanks.

**Comment by quilligana** [comment]
Hi @taivo. Great work on the plugin. Thanks.

Run into a bit of a roadblock with `ParsePushPlugin.on('openPN', callback)` though. All works fine on iOS. On Android, 'openPN' is called if the app is in the background. The problem arises with a full coldstart as noted previously in this thread where the callback isn't getting hit. I've spent quite a while on this and figured that the plugin `jsCallback` within:

```
require('cordova/channel').onCordovaReady.subscribe(function() {
...
});
```

is not getting called either when a push notification is opened (I stuck some alerts into your code to test). I have tried increasing the `_coldStartDelayMs` value but obviously this doesn't matter as `softTrigger` isn't getting called in the first place. 

Is this something you have figured out some other way? Anyone else come across this particular case? Your help is greatly appreciated.

**Comment by taivo** [comment]
@quilligana, thank you for digging into the code and attempt to isolate the issue.

Strange that this issue has resurfaced. My plate is very full at the moment so chances are I won't be able to get to it until end of next week. I can tell you where I would start looking in case you want to make a PR.

At a high level, the following are the automatic interactions that happen for the cold start case:

-- The Parse Android SDK calls `ParsePushPluginReceiver:onPushOpen`. 
-- That function, in turn, calls the 2-param version of `ParsePushPlugin:jsCallback`. 
-- If the javascript side of this plugin is not yet ready (haven't yet registered a callback with the Android side, true for the cold start case), push notification content will be saved in to a queue.
-- When the javascript side successfully registers the callback, the queue is flushed by calling `ParsePushPlugin:flushPNQueue`.

All steps I mentioned above are done automatically by the plugin code. You don't need to do any manual registration or queue flushing.

That said, obviously something is not happening correctly. I would start my investigation by putting in log statements in `ParsePushPlugin:jsCallback` and `flushPNQueue`. For the cold start case, both of these functions are expected to run at least once.

Hope that helps you for the time being. I'll look into this in 2 weeks unless you beat me to it, which I hope you do :)

**Comment by quilligana** [comment]
Okay. Thanks for those pointers. Working on this at the moment. 

It seems it's not actually from a coldstart that this happens. It occurs when the app is exited by pressing the android back button. When a notification is received when the app is in this state, it logs that it's not in foreground and creates the notification tray entry. Then when the push is opened, the `onPushOpen` method is fired but never makes its way back to the `ParsePushPlugin:jsCallback`.

Trying to figure this out now. Anything obvious come to mind @taivo?
